/**
 * Los datos con los que se puebla la base local: 18 organizaciones y 18 Festivales.
 *
 * LOS FESTIVALES SON REALES y los municipios también: los códigos DIVIPOLA se leyeron de
 * `dbo.Divipola`, no se escribieron de memoria. Un código inventado no
 * falla al guardar —la columna admite cualquier cadena— pero deja el Festival fuera del mapa.
 *
 * LAS CONTRASEÑAS SON LITERALES Y ESTÁN AQUÍ A PROPÓSITO: son cuentas de una base local de
 * desarrollo que nunca se despliega. Si algún día esto sale de la máquina, estas cuentas se borran.
 */

export interface Organizacion {
  /** Se usa como nombre de la organización y como parte del correo. */
  nombre: string;
  nombreLegal: string;
  nit: string;
  responsable: string;
  documentoResponsable: string;
  correo: string;
  telefono: string;
  direccion: string;
  descripcion: string;
  sitioWeb: string;
  instagram: string;
  facebook: string;
  otroEnlace: string;
  departamento: string;
  municipio: string;
}

export interface Edicion {
  nombre: string;
  anio: string;
  fechaInicio: string;
  fechaFin: string;
}

export interface Festival {
  /** El correo de la organización que lo crea. */
  organizacion: string;
  nombre: string;
  descripcion: string;
  nivelCobertura: 'municipal' | 'departamental' | 'nacional';
  departamento: string;
  municipio: string;
  correoContacto: string;
  periodicidad: string;
  edicion: Edicion;
  /** `publicado` = se aprueba desde la consola; `en_revision` = se deja esperando decisión. */
  destino: 'publicado' | 'en_revision';
}

export const CLAVE = 'Pnmc2026*Local';

/**
 * Las dieciocho organizaciones.
 *
 * LA PRIMERA ES «Pruebas» y es la única con dos Festivales: la pidió el usuario como banco de
 * trabajo. La última, «Corporación Sonidos de la Sabana», NO tiene Festival a propósito: el panel
 * tiene que saber pintar una organización vacía, y hasta hoy no había ninguna con la que verlo.
 */
export const ORGANIZACIONES: Organizacion[] = [
  {
    nombre: 'Pruebas',
    nombreLegal: 'Organización de Pruebas del PNMC',
    nit: '900123456-1',
    responsable: 'Camila Restrepo Ortiz',
    documentoResponsable: '1020304050',
    correo: 'pruebas@pnmc.local',
    telefono: '6012345678',
    direccion: 'Calle 12 # 4-56, oficina 301',
    descripcion: 'Organización de trabajo del equipo del PNMC. Se usa para probar el circuito completo de registro, edición y revisión de Festivales.',
    sitioWeb: 'https://pruebas.pnmc.local',
    instagram: 'https://instagram.com/pnmc_pruebas',
    facebook: 'https://facebook.com/pnmcpruebas',
    otroEnlace: 'https://youtube.com/@pnmcpruebas',
    departamento: '11',
    municipio: '11001',
  },
  {
    nombre: 'Corporación de Festivales del Pacífico',
    nombreLegal: 'Corporación de Festivales del Pacífico Colombiano',
    nit: '900234567-2',
    responsable: 'Yuri Angulo Riascos',
    documentoResponsable: '1144556677',
    correo: 'pacifico@pnmc.local',
    telefono: '6022345678',
    direccion: 'Carrera 5 # 6-05, barrio San Antonio',
    descripcion: 'Corporación que organiza y acompaña festivales de músicas del Pacífico sur colombiano, con énfasis en marimba de chonta y cantos tradicionales.',
    sitioWeb: 'https://festivalespacifico.org.co',
    instagram: 'https://instagram.com/festivalespacifico',
    facebook: 'https://facebook.com/festivalespacifico',
    otroEnlace: 'https://youtube.com/@festivalespacifico',
    departamento: '76',
    municipio: '76001',
  },
  {
    nombre: 'Fundación Festival de la Leyenda Vallenata',
    nombreLegal: 'Fundación Festival de la Leyenda Vallenata',
    nit: '900345678-3',
    responsable: 'Rafael Molina Daza',
    documentoResponsable: '1155667788',
    correo: 'vallenata@pnmc.local',
    telefono: '6055123456',
    direccion: 'Calle 15 # 9-30, centro',
    descripcion: 'Fundación que custodia y organiza el certamen de acordeón, caja y guacharaca más antiguo del Caribe colombiano.',
    sitioWeb: 'https://festivalvallenato.com',
    instagram: 'https://instagram.com/festivalvallenato',
    facebook: 'https://facebook.com/festivalvallenato',
    otroEnlace: 'https://x.com/festivallenato',
    departamento: '20',
    municipio: '20001',
  },
  {
    nombre: 'Asociación Cultural del Porro',
    nombreLegal: 'Asociación Cultural del Porro de San Pelayo',
    nit: '900456789-4',
    responsable: 'Jorge Petro Hernández',
    documentoResponsable: '1166778899',
    correo: 'porro@pnmc.local',
    telefono: '6047812345',
    direccion: 'Calle 8 # 3-14, parque principal',
    descripcion: 'Asociación de bandas pelayeras que sostiene la tradición del porro en el bajo Sinú y forma nuevos intérpretes de viento y percusión.',
    sitioWeb: 'https://porrosanpelayo.org',
    instagram: 'https://instagram.com/porrosanpelayo',
    facebook: 'https://facebook.com/porrosanpelayo',
    otroEnlace: 'https://youtube.com/@porrosanpelayo',
    departamento: '23',
    municipio: '23686',
  },
  {
    nombre: 'Corporación Bambuco del Huila',
    nombreLegal: 'Corporación Cultural del Bambuco del Huila',
    nit: '900567890-5',
    responsable: 'Marleny Cuéllar Perdomo',
    documentoResponsable: '1177889900',
    correo: 'bambuco@pnmc.local',
    telefono: '6088712345',
    direccion: 'Carrera 5 # 21-81, barrio Altico',
    descripcion: 'Corporación que organiza el certamen folclórico del bambuco huilense y acompaña a las escuelas de danza y música del departamento.',
    sitioWeb: 'https://bambucohuila.org.co',
    instagram: 'https://instagram.com/bambucohuila',
    facebook: 'https://facebook.com/bambucohuila',
    otroEnlace: 'https://youtube.com/@bambucohuila',
    departamento: '41',
    municipio: '41001',
  },
  {
    nombre: 'Fundación Canto por la Vida',
    nombreLegal: 'Fundación Cultural Canto por la Vida',
    nit: '900678901-6',
    responsable: 'Álvaro Ramírez Sarmiento',
    documentoResponsable: '1188990011',
    correo: 'mononunez@pnmc.local',
    telefono: '6023456789',
    direccion: 'Calle 4 # 5-40, casa de la cultura',
    descripcion: 'Fundación que sostiene el concurso de músicas andinas colombianas y su archivo sonoro, con sede en el Valle del Cauca.',
    sitioWeb: 'https://mononunez.org',
    instagram: 'https://instagram.com/mononunezoficial',
    facebook: 'https://facebook.com/mononunezoficial',
    otroEnlace: 'https://youtube.com/@mononunez',
    departamento: '76',
    municipio: '76306',
  },
  {
    nombre: 'Fundación Guabina y Tiple',
    nombreLegal: 'Fundación Nacional de la Guabina y el Tiple',
    nit: '900789012-7',
    responsable: 'Gustavo Ardila Peña',
    documentoResponsable: '1199001122',
    correo: 'guabina@pnmc.local',
    telefono: '6076123456',
    direccion: 'Carrera 3 # 8-22, centro histórico',
    descripcion: 'Fundación santandereana dedicada a la guabina, el torbellino y la construcción artesanal del tiple.',
    sitioWeb: 'https://guabinaytiple.org.co',
    instagram: 'https://instagram.com/guabinaytiple',
    facebook: 'https://facebook.com/guabinaytiple',
    otroEnlace: 'https://youtube.com/@guabinaytiple',
    departamento: '68',
    municipio: '68861',
  },
  {
    nombre: 'Fundación Mompox Jazz',
    nombreLegal: 'Fundación Cultural Mompox Jazz',
    nit: '900890123-8',
    responsable: 'Daniela Trespalacios Ruiz',
    documentoResponsable: '1200112233',
    correo: 'mompoxjazz@pnmc.local',
    telefono: '6056851234',
    direccion: 'Calle de la Albarrada # 14-09',
    descripcion: 'Fundación que reúne al jazz con las músicas de la depresión momposina en la ribera del río Magdalena.',
    sitioWeb: 'https://mompoxjazz.com',
    instagram: 'https://instagram.com/mompoxjazz',
    facebook: 'https://facebook.com/mompoxjazz',
    otroEnlace: 'https://youtube.com/@mompoxjazz',
    departamento: '13',
    municipio: '13468',
  },
  {
    nombre: 'Fundación Salvi Colombia',
    nombreLegal: 'Fundación Salvi Colombia',
    nit: '900901234-9',
    responsable: 'Julia Salvi Restrepo',
    documentoResponsable: '1211223344',
    correo: 'cartagena@pnmc.local',
    telefono: '6056641234',
    direccion: 'Centro, calle del Cuartel # 36-77',
    descripcion: 'Fundación que organiza el encuentro internacional de música académica de Cartagena y su programa de formación para jóvenes intérpretes.',
    sitioWeb: 'https://cartagenamusicfestival.com',
    instagram: 'https://instagram.com/cartagenamusicfestival',
    facebook: 'https://facebook.com/cartagenamusicfestival',
    otroEnlace: 'https://youtube.com/@cartagenamusicfestival',
    departamento: '13',
    municipio: '13001',
  },
  {
    nombre: 'Corporación Bandas de Paipa',
    nombreLegal: 'Corporación del Concurso Nacional de Bandas de Paipa',
    nit: '901012345-0',
    responsable: 'Hernando Vargas Bohórquez',
    documentoResponsable: '1222334455',
    correo: 'paipa@pnmc.local',
    telefono: '6087850123',
    direccion: 'Carrera 21 # 25-40, parque Jaime Rook',
    descripcion: 'Corporación boyacense que organiza el concurso nacional de bandas de viento y su escuela de formación permanente.',
    sitioWeb: 'https://bandasdepaipa.gov.co',
    instagram: 'https://instagram.com/bandasdepaipa',
    facebook: 'https://facebook.com/bandasdepaipa',
    otroEnlace: 'https://youtube.com/@bandasdepaipa',
    departamento: '15',
    municipio: '15516',
  },
  {
    nombre: 'Fundación Musical de Colombia',
    nombreLegal: 'Fundación Musical de Colombia',
    nit: '901123456-1',
    responsable: 'Beatriz Oviedo Lozano',
    documentoResponsable: '1233445566',
    correo: 'ibague@pnmc.local',
    telefono: '6082612345',
    direccion: 'Carrera 3 # 11-32, conservatorio',
    descripcion: 'Fundación tolimense que organiza el certamen nacional de música colombiana y sostiene el archivo del pasillo y el bambuco.',
    sitioWeb: 'https://fundacionmusicaldecolombia.com',
    instagram: 'https://instagram.com/fmcolombia',
    facebook: 'https://facebook.com/fmcolombia',
    otroEnlace: 'https://youtube.com/@fmcolombia',
    departamento: '73',
    municipio: '73001',
  },
  {
    nombre: 'Fundación Gaitas de Ovejas',
    nombreLegal: 'Fundación Festival Nacional de Gaitas de Ovejas',
    nit: '901234567-2',
    responsable: 'Nolberto Meza Contreras',
    documentoResponsable: '1244556677',
    correo: 'gaitas@pnmc.local',
    telefono: '6052861234',
    direccion: 'Calle 20 # 19-10, plaza central',
    descripcion: 'Fundación sucreña que sostiene la gaita larga y corta de los Montes de María y forma gaiteros desde la infancia.',
    sitioWeb: 'https://gaitasdeovejas.org',
    instagram: 'https://instagram.com/gaitasdeovejas',
    facebook: 'https://facebook.com/gaitasdeovejas',
    otroEnlace: 'https://youtube.com/@gaitasdeovejas',
    departamento: '70',
    municipio: '70508',
  },
  {
    nombre: 'Corporación Currulao del Pacífico Nariñense',
    nombreLegal: 'Corporación Cultural Currulao del Pacífico Nariñense',
    nit: '901345678-3',
    responsable: 'Sandra Quiñones Castillo',
    documentoResponsable: '1255667788',
    correo: 'currulao@pnmc.local',
    telefono: '6027271234',
    direccion: 'Calle Sucre # 5-18, barrio Pradomar',
    descripcion: 'Corporación de Tumaco que organiza encuentros de currulao, bunde y arrullo con las comunidades del litoral nariñense.',
    sitioWeb: 'https://currulaonarino.org',
    instagram: 'https://instagram.com/currulaonarino',
    facebook: 'https://facebook.com/currulaonarino',
    otroEnlace: 'https://youtube.com/@currulaonarino',
    departamento: '52',
    municipio: '52835',
  },
  {
    nombre: 'Corporación Cultural Llanera',
    nombreLegal: 'Corporación Cultural del Joropo Llanero',
    nit: '901456789-4',
    responsable: 'Wilmer Gaitán Rivera',
    documentoResponsable: '1266778899',
    correo: 'joropo@pnmc.local',
    telefono: '6086701234',
    direccion: 'Carrera 33 # 38-20, barrio Barzal',
    descripcion: 'Corporación metense que organiza el torneo de joropo y sostiene escuelas de arpa, cuatro, maracas y baile recio.',
    sitioWeb: 'https://torneodeljoropo.com',
    instagram: 'https://instagram.com/torneodeljoropo',
    facebook: 'https://facebook.com/torneodeljoropo',
    otroEnlace: 'https://youtube.com/@torneodeljoropo',
    departamento: '50',
    municipio: '50001',
  },
  {
    nombre: 'Fundación Cuna de Acordeones',
    nombreLegal: 'Fundación Festival Cuna de Acordeones',
    nit: '901567890-5',
    responsable: 'Emiro Zuleta Baquero',
    documentoResponsable: '1277889900',
    correo: 'acordeones@pnmc.local',
    telefono: '6053741234',
    direccion: 'Calle 6 # 7-25, centro',
    descripcion: 'Fundación guajira que sostiene el certamen de acordeoneros de Villanueva y la escuela de música vallenata del sur de La Guajira.',
    sitioWeb: 'https://cunadeacordeones.org',
    instagram: 'https://instagram.com/cunadeacordeones',
    facebook: 'https://facebook.com/cunadeacordeones',
    otroEnlace: 'https://youtube.com/@cunadeacordeones',
    departamento: '44',
    municipio: '44874',
  },
  {
    nombre: 'Instituto Distrital de las Artes',
    nombreLegal: 'Instituto Distrital de las Artes — Idartes',
    nit: '901678901-6',
    responsable: 'Catalina Valencia Tobón',
    documentoResponsable: '1288990011',
    correo: 'idartes@pnmc.local',
    telefono: '6013795750',
    direccion: 'Carrera 8 # 15-46, centro',
    descripcion: 'Instituto distrital que programa los festivales al parque de Bogotá y administra los escenarios públicos de la ciudad.',
    sitioWeb: 'https://idartes.gov.co',
    instagram: 'https://instagram.com/idartes',
    facebook: 'https://facebook.com/idartes',
    otroEnlace: 'https://youtube.com/@idartes',
    departamento: '11',
    municipio: '11001',
  },
  {
    nombre: 'Fundación Cultural Nueva Música',
    nombreLegal: 'Fundación Cultural Nueva Música del Caribe',
    nit: '901789012-7',
    responsable: 'Iván Movilla Peralta',
    documentoResponsable: '1299001122',
    correo: 'barranquijazz@pnmc.local',
    telefono: '6053601234',
    direccion: 'Carrera 54 # 72-80, barrio El Prado',
    descripcion: 'Fundación barranquillera que organiza el encuentro de jazz del Caribe y su programa de clases magistrales.',
    sitioWeb: 'https://barranquijazz.com.co',
    instagram: 'https://instagram.com/barranquijazz',
    facebook: 'https://facebook.com/barranquijazz',
    otroEnlace: 'https://youtube.com/@barranquijazz',
    departamento: '08',
    municipio: '08001',
  },
  {
    nombre: 'Corporación Sonidos de la Sabana',
    nombreLegal: 'Corporación Cultural Sonidos de la Sabana',
    nit: '901890123-8',
    responsable: 'Luz Elena Bermúdez Ríos',
    documentoResponsable: '1300112233',
    correo: 'sabana@pnmc.local',
    telefono: '6018901234',
    direccion: 'Calle 80 # 45-12, oficina 202',
    descripcion: 'Corporación recién inscrita que acompaña procesos musicales comunitarios en la sabana de Bogotá. Todavía no ha registrado ningún Festival.',
    sitioWeb: 'https://sonidosdelasabana.org',
    instagram: 'https://instagram.com/sonidosdelasabana',
    facebook: 'https://facebook.com/sonidosdelasabana',
    otroEnlace: 'https://youtube.com/@sonidosdelasabana',
    departamento: '11',
    municipio: '11001',
  },
];

/**
 * Los dieciocho Festivales.
 *
 * QUINCE VAN A `publicado` y tres se quedan `en_revision`, que es lo que pidió el usuario. Los tres
 * que se quedan esperando son de organizaciones distintas a propósito: una bandeja con tres filas
 * de la misma organización no enseña nada sobre cómo se lee la bandeja.
 */
export const FESTIVALES: Festival[] = [
  {
    organizacion: 'pruebas@pnmc.local',
    nombre: 'Fiestas de San Pacho',
    descripcion: 'Fiestas franciscanas de Quibdó: doce días de chirimía chocoana, comparsas por barrio y procesión por el río Atrato. Declaradas patrimonio inmaterial de la humanidad.',
    nivelCobertura: 'departamental',
    departamento: '27',
    municipio: '27001',
    correoContacto: 'sanpacho@pruebas.pnmc.local',
    periodicidad: 'anual',
    edicion: { nombre: 'San Pacho 2026 · Chirimía y río', anio: '2026', fechaInicio: '2026-09-20', fechaFin: '2026-10-05' },
    destino: 'publicado',
  },
  {
    organizacion: 'pruebas@pnmc.local',
    nombre: 'Festival Francisco el Hombre',
    descripcion: 'Encuentro de juglares del vallenato tradicional en Riohacha, con las cuatro modalidades de acordeón y una muestra de composición inédita.',
    nivelCobertura: 'departamental',
    departamento: '44',
    municipio: '44001',
    correoContacto: 'franciscoelhombre@pruebas.pnmc.local',
    periodicidad: 'anual',
    edicion: { nombre: 'Francisco el Hombre 2026 · Los cuatro aires', anio: '2026', fechaInicio: '2026-07-10', fechaFin: '2026-07-14' },
    destino: 'en_revision',
  },
  {
    organizacion: 'pacifico@pnmc.local',
    nombre: 'Festival de Música del Pacífico Petronio Álvarez',
    descripcion: 'El mayor encuentro de músicas del Pacífico colombiano. Concursa en cuatro modalidades: marimba y cantos tradicionales, chirimía, violines caucanos y libre.',
    nivelCobertura: 'municipal',
    departamento: '76',
    municipio: '76001',
    correoContacto: 'petronio@festivalespacifico.org.co',
    periodicidad: 'anual',
    edicion: { nombre: 'Petronio Álvarez 2026 · Trenzando raíces', anio: '2026', fechaInicio: '2026-08-12', fechaFin: '2026-08-17' },
    destino: 'publicado',
  },
  {
    organizacion: 'vallenata@pnmc.local',
    nombre: 'Festival de la Leyenda Vallenata',
    descripcion: 'Certamen de acordeón, caja y guacharaca de Valledupar. Reúne las cuatro modalidades del vallenato tradicional: son, paseo, merengue y puya.',
    nivelCobertura: 'municipal',
    departamento: '20',
    municipio: '20001',
    correoContacto: 'contacto@festivalvallenato.com',
    periodicidad: 'anual',
    edicion: { nombre: 'Leyenda Vallenata 2026 · 59.ª edición', anio: '2026', fechaInicio: '2026-04-26', fechaFin: '2026-04-30' },
    destino: 'publicado',
  },
  {
    organizacion: 'porro@pnmc.local',
    nombre: 'Festival Nacional del Porro',
    descripcion: 'Encuentro de bandas pelayeras del bajo Sinú. Concursan bandas infantiles, juveniles y mayores en porro tapa’o y porro palitia’o.',
    nivelCobertura: 'municipal',
    departamento: '23',
    municipio: '23686',
    correoContacto: 'contacto@porrosanpelayo.org',
    periodicidad: 'anual',
    edicion: { nombre: 'Porro 2026 · Bandas del Sinú', anio: '2026', fechaInicio: '2026-06-27', fechaFin: '2026-07-01' },
    destino: 'publicado',
  },
  {
    organizacion: 'bambuco@pnmc.local',
    nombre: 'Festival Folclórico y Reinado Nacional del Bambuco',
    descripcion: 'Certamen huilense de bambuco y sanjuanero, con muestra de danza, música de cuerdas andinas y desfile por las comunas de Neiva.',
    nivelCobertura: 'municipal',
    departamento: '41',
    municipio: '41001',
    correoContacto: 'contacto@bambucohuila.org.co',
    periodicidad: 'anual',
    edicion: { nombre: 'Bambuco 2026 · San Juan y San Pedro', anio: '2026', fechaInicio: '2026-06-18', fechaFin: '2026-06-30' },
    destino: 'publicado',
  },
  {
    organizacion: 'mononunez@pnmc.local',
    nombre: 'Festival Mono Núñez',
    descripcion: 'Concurso nacional de músicas andinas colombianas en Ginebra, Valle. Categorías instrumental y vocal, con muestra de obras inéditas.',
    nivelCobertura: 'municipal',
    departamento: '76',
    municipio: '76306',
    correoContacto: 'contacto@mononunez.org',
    periodicidad: 'anual',
    edicion: { nombre: 'Mono Núñez 2026 · Cuerdas del valle', anio: '2026', fechaInicio: '2026-05-28', fechaFin: '2026-05-31' },
    destino: 'publicado',
  },
  {
    organizacion: 'guabina@pnmc.local',
    nombre: 'Festival Nacional de la Guabina y el Tiple',
    descripcion: 'Encuentro veleño de guabina, torbellino y tiple, con concurso de duetos, exposición de luthería y muestra de bebidas y dulces tradicionales.',
    nivelCobertura: 'municipal',
    departamento: '68',
    municipio: '68861',
    correoContacto: 'contacto@guabinaytiple.org.co',
    periodicidad: 'anual',
    edicion: { nombre: 'Guabina y Tiple 2026 · Torbellino veleño', anio: '2026', fechaInicio: '2026-08-07', fechaFin: '2026-08-11' },
    destino: 'publicado',
  },
  {
    organizacion: 'mompoxjazz@pnmc.local',
    nombre: 'Mompox Jazz Festival',
    descripcion: 'Encuentro de jazz en la Santa Cruz de Mompox, con escenarios en la Albarrada y diálogo entre el jazz y las músicas de tambora del Magdalena.',
    nivelCobertura: 'municipal',
    departamento: '13',
    municipio: '13468',
    correoContacto: 'contacto@mompoxjazz.com',
    periodicidad: 'anual',
    edicion: { nombre: 'Mompox Jazz 2026 · Río y metales', anio: '2026', fechaInicio: '2026-09-25', fechaFin: '2026-09-28' },
    destino: 'publicado',
  },
  {
    organizacion: 'cartagena@pnmc.local',
    nombre: 'Festival Internacional de Música de Cartagena',
    descripcion: 'Encuentro de música académica en el centro histórico de Cartagena, con orquestas invitadas, música de cámara y conciertos didácticos gratuitos.',
    nivelCobertura: 'municipal',
    departamento: '13',
    municipio: '13001',
    correoContacto: 'contacto@cartagenamusicfestival.com',
    periodicidad: 'anual',
    edicion: { nombre: 'Cartagena 2026 · El clasicismo vienés', anio: '2026', fechaInicio: '2026-01-09', fechaFin: '2026-01-17' },
    destino: 'publicado',
  },
  {
    organizacion: 'paipa@pnmc.local',
    nombre: 'Concurso Nacional de Bandas de Paipa',
    descripcion: 'Certamen boyacense de bandas de viento. Concursan categorías infantil, juvenil, mayores y especial, con obra obligada y obra libre.',
    nivelCobertura: 'municipal',
    departamento: '15',
    municipio: '15516',
    correoContacto: 'contacto@bandasdepaipa.gov.co',
    periodicidad: 'anual',
    edicion: { nombre: 'Bandas de Paipa 2026 · 52.º concurso', anio: '2026', fechaInicio: '2026-09-11', fechaFin: '2026-09-14' },
    destino: 'publicado',
  },
  {
    organizacion: 'ibague@pnmc.local',
    nombre: 'Festival Nacional de la Música Colombiana',
    descripcion: 'Certamen de Ibagué dedicado al bambuco, el pasillo y la guabina, con concurso de intérpretes y de obra inédita, y foro de compositores.',
    nivelCobertura: 'municipal',
    departamento: '73',
    municipio: '73001',
    correoContacto: 'contacto@fundacionmusicaldecolombia.com',
    periodicidad: 'anual',
    edicion: { nombre: 'Música Colombiana 2026 · 40.ª edición', anio: '2026', fechaInicio: '2026-03-20', fechaFin: '2026-03-28' },
    destino: 'publicado',
  },
  {
    organizacion: 'gaitas@pnmc.local',
    nombre: 'Festival Nacional de Gaitas Francisco Llirene',
    descripcion: 'Encuentro de gaita larga y corta de los Montes de María, con concurso de conjuntos de gaita, tambora y llamador, y taller de construcción de gaitas.',
    nivelCobertura: 'municipal',
    departamento: '70',
    municipio: '70508',
    correoContacto: 'contacto@gaitasdeovejas.org',
    periodicidad: 'anual',
    edicion: { nombre: 'Gaitas 2026 · Montes de María', anio: '2026', fechaInicio: '2026-10-15', fechaFin: '2026-10-19' },
    destino: 'publicado',
  },
  {
    organizacion: 'currulao@pnmc.local',
    nombre: 'Festival del Currulao',
    descripcion: 'Encuentro de músicas del litoral nariñense en Tumaco: currulao, bunde, juga y arrullo, con marimba de chonta, cununos y guasás.',
    nivelCobertura: 'departamental',
    departamento: '52',
    municipio: '52835',
    correoContacto: 'contacto@currulaonarino.org',
    periodicidad: 'anual',
    edicion: { nombre: 'Currulao 2026 · Marimba y guasá', anio: '2026', fechaInicio: '2026-08-14', fechaFin: '2026-08-17' },
    destino: 'publicado',
  },
  {
    organizacion: 'joropo@pnmc.local',
    nombre: 'Torneo Internacional del Joropo',
    descripcion: 'Certamen llanero de Villavicencio: arpa, cuatro y maracas, con concurso de baile recio, contrapunteo y voz recia masculina y femenina.',
    nivelCobertura: 'departamental',
    departamento: '50',
    municipio: '50001',
    correoContacto: 'contacto@torneodeljoropo.com',
    periodicidad: 'anual',
    edicion: { nombre: 'Joropo 2026 · Arpa y contrapunteo', anio: '2026', fechaInicio: '2026-06-25', fechaFin: '2026-06-29' },
    destino: 'publicado',
  },
  {
    organizacion: 'acordeones@pnmc.local',
    nombre: 'Festival Cuna de Acordeones',
    descripcion: 'Certamen de Villanueva, La Guajira, dedicado al acordeón vallenato tradicional, con concurso de acordeoneros aficionados, juveniles y profesionales.',
    nivelCobertura: 'municipal',
    departamento: '44',
    municipio: '44874',
    correoContacto: 'contacto@cunadeacordeones.org',
    periodicidad: 'anual',
    edicion: { nombre: 'Cuna de Acordeones 2026 · 47.ª edición', anio: '2026', fechaInicio: '2026-08-19', fechaFin: '2026-08-23' },
    destino: 'publicado',
  },
  {
    organizacion: 'idartes@pnmc.local',
    nombre: 'Rock al Parque',
    descripcion: 'Festival gratuito de músicas fuertes de Bogotá, el mayor al aire libre de América Latina, con bandas distritales, nacionales e internacionales.',
    nivelCobertura: 'nacional',
    departamento: '11',
    municipio: '11001',
    correoContacto: 'rockalparque@idartes.gov.co',
    periodicidad: 'anual',
    edicion: { nombre: 'Rock al Parque 2026 · 32.ª edición', anio: '2026', fechaInicio: '2026-11-14', fechaFin: '2026-11-16' },
    destino: 'en_revision',
  },
  {
    organizacion: 'barranquijazz@pnmc.local',
    nombre: 'Barranquijazz',
    descripcion: 'Encuentro de jazz y músicas del Caribe en Barranquilla, con clases magistrales, escenarios de calle y homenajes a la tradición caribeña.',
    nivelCobertura: 'nacional',
    departamento: '08',
    municipio: '08001',
    correoContacto: 'contacto@barranquijazz.com.co',
    periodicidad: 'anual',
    edicion: { nombre: 'Barranquijazz 2026 · 30.ª edición', anio: '2026', fechaInicio: '2026-09-03', fechaFin: '2026-09-06' },
    destino: 'en_revision',
  },
];
