/*
  Estado inicial del módulo de Festivales en la base SIMUS del Ministerio: las 22 tablas
  ART_MUS_* y sus catálogos, tal como los entregó la exportación de SSMS.

  En la base del Ministerio esta versión NO se ejecuta: ya está instalada y se registra con
  `flyway baseline` (baselineVersion = 1). Solo corre en una instalación desde cero, que además
  necesita las tablas ART_MUSICA_USUARIO y BAS_ZONAS_GEOGRAFICAS, propias de SIMUS.

  Diferencias con la exportación recibida: sin `USE`, sin los registros de prueba de festivales y
  versiones, y sin las dos tablas ART_MUS_TIP_*, que pertenecen al módulo de Entidades.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[creado_por] [int] NULL,
	[NOMBRE_FESTIVAL] [varchar](150) NULL,
	[VERSIONES_REALIZADAS] [int] NULL,
	[FECHA_ULTIMA_VERSION] [datetime] NULL,
	[DESCRIPCION_FESTIVAL] [nvarchar](4000) NULL,
	[CORREO_CONTACTO] [varchar](300) NULL,
	[INSTAGRAM] [varchar](300) NULL,
	[FACEBOOK] [varchar](300) NULL,
	[PAGINA_WEB] [varchar](300) NULL,
	[OTRO_ENLACE] [varchar](300) NULL,
	[CELULAR] [varchar](300) NULL,
	[OBSERVACIONES_CONTACTO] [varchar](300) NULL,
	[FECHA_ENVIO] [datetime] NULL,
	[ID_ESTADO] [int] NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_ENTIDADES_ALIADAS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_ENTIDAD_ALIADA] [nvarchar](150) NULL,
	[ID_NATURALEZA] [int] NULL,
	[ID_FESTIVAL] [int] NULL,
	[CORREO_ENTIDAD] [nvarchar](150) NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_ENTIDADES_ALIADAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_ESTADO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FESTIVALES_ESTADO] [nvarchar](50) NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_ESTADO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EXPRESION_ARTISTICA] [nvarchar](50) NOT NULL,
	[ACTIVO] [bit] NOT NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_EXPRESIONXVERSION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_VERSION] [int] NOT NULL,
	[ID_EXPRESION_ARTISTICA] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_EXPRESIONXVERSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FUENTE_FINANCIACION] [nvarchar](50) NULL,
	[ACTIVO] [bit] NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_FUENTE_FINANCIACION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MODALIDAD_PARTICIPACION] [nvarchar](50) NOT NULL,
	[ACTIVO] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_VERSION] [int] NOT NULL,
	[ID_MODALIDAD] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NATURALEZA] [nchar](20) NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_REGION_OCAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_REGION_OCAD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TIPO_ORGANIZADOR] [nvarchar](50) NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TIPOLOGIA] [nvarchar](50) NOT NULL,
	[ACTIVO] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_TIPOLOGIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_VERSION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_FESTIVAL] [int] NULL,
	[VERSION_FESTIVAL] [int] NULL,
	[NOMBRE_VERSION] [varchar](250) NULL,
	[DESCRIPCION_VERSION] [varchar](3000) NULL,
	[PRACTICAS_MUSICALES_CONGREGA] [varchar](250) NULL,
	[FECHA_INICIO] [nchar](10) NULL,
	[FECHA_FIN] [nchar](10) NULL,
	[ID_TIPOLOGIA] [int] NULL,
	[OTRA_TIPOLOGIA] [nvarchar](50) NULL,
	[OTRA_MODALIDAD_PARTICIPACION] [nvarchar](50) NULL,
	[OTRA_EXPRESION_ARTISTICA] [nvarchar](50) NULL,
	[ID_FUENTE_FINANCIACION] [int] NULL,
	[ID_FUENTE_FINANCIACION_SECUNDARIA] [int] NULL,
	[OTRA_FUENTE_FINANCIACION_PRIMARIA] [nvarchar](50) NULL,
	[OTRA_FUENTE_FINANCIACION_SECUNDARIA] [nvarchar](50) NULL,
	[USO_ESTAMPILLA_PROCULTURA] [bit] NULL,
	[DIRECTOR] [nvarchar](250) NULL,
	[PERTENECE_ORG_COLETIVA] [bit] NULL,
	[NOMBRE_ORGANIZACION] [nvarchar](250) NULL,
	[ID_TIPO_ORGANIZADOR] [int] NULL,
	[OTRO_TIPO_ORGANIZADOR] [nvarchar](50) NULL,
	[CORREO_CONTACTO] [nvarchar](500) NULL,
	[INSTAGRAM] [nvarchar](500) NULL,
	[FACEBOOK] [nvarchar](500) NULL,
	[PAGINA_WEB] [nvarchar](500) NULL,
	[OTRO_ENLACE] [nvarchar](500) NULL,
	[TELEFONO_CELULAR] [varchar](50) NULL,
	[OBSERVACIONES_CONTACTO] [nvarchar](150) NULL,
	[OBSERVACIONES_RECHAZO] [nvarchar](4000) NULL,
	[ID_ESTADO] [int] NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_VERSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_ZONA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MUS_FESTIVALES_ZONA] [nvarchar](50) NOT NULL,
	[ES_RURAL] [bit] NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_ZONA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRPCION_ZONA_TITULACION_COLECTIVA] [nvarchar](250) NOT NULL,
	[ACTIVO] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_VERSION] [int] NOT NULL,
	[ZON_ID] [varchar](5) NOT NULL,
	[ID_ZONA] [int] NULL,
	[ID_TITULACION_COLECTIVA] [int] NULL,
 CONSTRAINT [PK_ART_MUS_LOCALIZACIONXVERSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_MATERIALMULTIMEDIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_VERSION] [int] NULL,
	[URL_ARCHIVO] [nvarchar](250) NULL,
	[DESCRIPCION_ARCHIVO] [nvarchar](250) NULL,
 CONSTRAINT [PK_ART_MUS_MATERIALMULTIMEDIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_TERRITORIOS_SONOROS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TERRITORIOS_SONOROS] [nvarchar](250) NULL,
 CONSTRAINT [PK_ART_MUS_TERRITORIOS_SONOROS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_TERRITORIOS_SONOROSXVERSION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_TERRITORIOS_SONOROS] [int] NULL,
	[ID_VERSION] [int] NULL,
 CONSTRAINT [PK_ART_MUS_TERRITORIOS_SONOROSXVERSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_TIPOINGRESO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TIPO_INGRESO] [nvarchar](50) NULL,
 CONSTRAINT [PK_ART_MUS_TIPOINGRESO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_TIPOINGRESOXVERSION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_TIPOINGRESO] [int] NULL,
	[IDVERSION] [int] NULL,
 CONSTRAINT [PK_ART_MUS_TIPOINGRESOXVERSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ART_MUS_ZONAXREGION_OCAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ZON_ID] [varchar](5) NOT NULL,
	[REGION_OCAD_ID] [int] NOT NULL,
 CONSTRAINT [PK_ART_MUS_ZONAXREGION_OCAD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_ESTADO] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_ESTADO] ([ID], [FESTIVALES_ESTADO]) VALUES (1, N'Borrador')
INSERT [dbo].[ART_MUS_FESTIVALES_ESTADO] ([ID], [FESTIVALES_ESTADO]) VALUES (2, N'Enviado')
INSERT [dbo].[ART_MUS_FESTIVALES_ESTADO] ([ID], [FESTIVALES_ESTADO]) VALUES (3, N'Solicitud de aclaraciones')
INSERT [dbo].[ART_MUS_FESTIVALES_ESTADO] ([ID], [FESTIVALES_ESTADO]) VALUES (4, N'Aprobado')
INSERT [dbo].[ART_MUS_FESTIVALES_ESTADO] ([ID], [FESTIVALES_ESTADO]) VALUES (5, N'Rechazado')
INSERT [dbo].[ART_MUS_FESTIVALES_ESTADO] ([ID], [FESTIVALES_ESTADO]) VALUES (6, N'Archivado')
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_ESTADO] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (1, N'MÚSICA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (2, N'DANZA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (3, N'CULINARIA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (4, N'ARTESANÍA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (5, N'CESTERÍA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (6, N'NARRACIÓN', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (7, N'CUENTERÍA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (9, N'IMPROVISACIÓN', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (11, N'OTRA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (12, N'NINGUNA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID], [EXPRESION_ARTISTICA], [ACTIVO]) VALUES (13, N'ARTES PLÁSTICAS', 1)
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (1, N'APORTES PRIVADOS', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (2, N'BOLETERÍA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (3, N'ESTÍMULOS', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (4, N'CONCERTACIÓN', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (5, N'MINCULTURA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (6, N'GOBERNACIÓN', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (7, N'ALCALDÍA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (8, N'RECURSOS PROPIOS', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID], [FUENTE_FINANCIACION], [ACTIVO]) VALUES (9, N'OTRA', 1)
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] ([ID], [MODALIDAD_PARTICIPACION], [ACTIVO]) VALUES (1, N'CONCURSO', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] ([ID], [MODALIDAD_PARTICIPACION], [ACTIVO]) VALUES (3, N'INVITADOS PAGOS', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] ([ID], [MODALIDAD_PARTICIPACION], [ACTIVO]) VALUES (4, N'INVITADOS SIN PAGA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] ([ID], [MODALIDAD_PARTICIPACION], [ACTIVO]) VALUES (6, N'POR CONVOCATORIA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] ([ID], [MODALIDAD_PARTICIPACION], [ACTIVO]) VALUES (7, N'OTRA', 1)
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD] ([ID], [NATURALEZA]) VALUES (1, N'PUBLICO             ')
INSERT [dbo].[ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD] ([ID], [NATURALEZA]) VALUES (2, N'PRIVADO             ')
INSERT [dbo].[ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD] ([ID], [NATURALEZA]) VALUES (3, N'MIXTO               ')
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] ([ID], [DESCRIPCION]) VALUES (1, N'CARIBE')
INSERT [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] ([ID], [DESCRIPCION]) VALUES (2, N'CENTRO ORIENTE')
INSERT [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] ([ID], [DESCRIPCION]) VALUES (3, N'EJE CAFETERO')
INSERT [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] ([ID], [DESCRIPCION]) VALUES (4, N'PACIFICO')
INSERT [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] ([ID], [DESCRIPCION]) VALUES (5, N'CENTRO SUR')
INSERT [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] ([ID], [DESCRIPCION]) VALUES (6, N'LLANO')
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ([ID], [TIPO_ORGANIZADOR]) VALUES (1, N'ENTIDAD PÚBLICA / ALCALDÍA')
INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ([ID], [TIPO_ORGANIZADOR]) VALUES (2, N'ENTIDAD PÚBLICA / GOBERNACIÓN')
INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ([ID], [TIPO_ORGANIZADOR]) VALUES (3, N'FUNDACIÓN')
INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ([ID], [TIPO_ORGANIZADOR]) VALUES (4, N'MUSEO')
INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ([ID], [TIPO_ORGANIZADOR]) VALUES (5, N'CASA CULTURAL')
INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ([ID], [TIPO_ORGANIZADOR]) VALUES (6, N'COMUNITARIO')
INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ([ID], [TIPO_ORGANIZADOR]) VALUES (7, N'MIXTO')
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (2, N'FIESTA POPULAR', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (4, N'CELEBRACIÓN RELIGIOSA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (5, N'FESTIVAL DE MÚSICA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (6, N'REINADO', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (7, N'FERIA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (8, N'CONFERENCIA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (9, N'MERCADO', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (10, N'MERCADOS CULTURALES', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (12, N'ENCUENTROS', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID], [TIPOLOGIA], [ACTIVO]) VALUES (14, N'OTRA', 1)
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_ZONA] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_ZONA] ([ID], [MUS_FESTIVALES_ZONA], [ES_RURAL]) VALUES (1, N'RURAL', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_ZONA] ([ID], [MUS_FESTIVALES_ZONA], [ES_RURAL]) VALUES (2, N'URBANO', 0)
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_ZONA] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA] ON 

INSERT [dbo].[ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA] ([ID], [DESCRPCION_ZONA_TITULACION_COLECTIVA], [ACTIVO]) VALUES (2, N'CONSEJO COMUNITARIO', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA] ([ID], [DESCRPCION_ZONA_TITULACION_COLECTIVA], [ACTIVO]) VALUES (3, N'RESGUARDO INDIGENA', 1)
INSERT [dbo].[ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA] ([ID], [DESCRPCION_ZONA_TITULACION_COLECTIVA], [ACTIVO]) VALUES (4, N'NO APLICA', 1)
SET IDENTITY_INSERT [dbo].[ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ON 

INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (1, N'TS Cantos, Pitos y Tambores')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (2, N'TS Canta y Torbellino')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (3, N'TS Rajaleña y Cucamba')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (4, N'TS Marimba')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (5, N'TS Flautas, Cuerdas y Tambores Sureños')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (6, N'TS Chirimía')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (7, N'TS Joropo')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (8, N'TS Trova y Parranda')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (9, N'TS Amazonas')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (10, N'TS Insular')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (11, N'TS Prácticas de Pueblos Indígenas')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (12, N'TS Músicas Urbanas, Alternativas e Independientes (MUAI)')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (13, N'TS Comunidades Académicas')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (14, N'TS Rrom')
INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID], [TERRITORIOS_SONOROS]) VALUES (15, N'N/A')
SET IDENTITY_INSERT [dbo].[ART_MUS_TERRITORIOS_SONOROS] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_TIPOINGRESO] ON 

INSERT [dbo].[ART_MUS_TIPOINGRESO] ([ID], [TIPO_INGRESO]) VALUES (1, N'Entrada libre (sin boletería)')
INSERT [dbo].[ART_MUS_TIPOINGRESO] ([ID], [TIPO_INGRESO]) VALUES (2, N'Entrada gratuita (con boletería)')
INSERT [dbo].[ART_MUS_TIPOINGRESO] ([ID], [TIPO_INGRESO]) VALUES (3, N'Boletería paga')
INSERT [dbo].[ART_MUS_TIPOINGRESO] ([ID], [TIPO_INGRESO]) VALUES (4, N'Sin público (transmisión en vivo)')
SET IDENTITY_INSERT [dbo].[ART_MUS_TIPOINGRESO] OFF
GO
SET IDENTITY_INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ON 

INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (1, N'44', 1)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (2, N'20', 1)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (3, N'47', 1)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (4, N'08', 1)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (5, N'70', 1)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (6, N'13', 1)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (7, N'23', 1)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (8, N'54', 2)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (9, N'68', 2)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (10, N'15', 2)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (11, N'25', 2)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (12, N'11', 2)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (13, N'05', 3)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (14, N'17', 3)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (15, N'66', 3)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (16, N'63', 3)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (17, N'27', 4)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (18, N'76', 4)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (19, N'19', 4)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (20, N'52', 4)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (21, N'73', 5)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (22, N'41', 5)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (23, N'18', 5)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (24, N'86', 5)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (25, N'91', 5)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (26, N'81', 6)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (27, N'85', 6)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (28, N'50', 6)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (29, N'99', 6)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (30, N'95', 6)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (31, N'94', 6)
INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] ([ID], [ZON_ID], [REGION_OCAD_ID]) VALUES (32, N'97', 6)
SET IDENTITY_INSERT [dbo].[ART_MUS_ZONAXREGION_OCAD] OFF
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_ART_MUS_FESTIVALES_ESTADO] FOREIGN KEY([ID_ESTADO])
REFERENCES [dbo].[ART_MUS_FESTIVALES_ESTADO] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_ART_MUS_FESTIVALES_ESTADO]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_ART_MUSICA_USUARIO] FOREIGN KEY([creado_por])
REFERENCES [dbo].[ART_MUSICA_USUARIO] ([Id])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_ART_MUSICA_USUARIO]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_ENTIDADES_ALIADAS]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_ENTIDADES_ALIADAS_ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD] FOREIGN KEY([ID_NATURALEZA])
REFERENCES [dbo].[ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_ENTIDADES_ALIADAS] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_ENTIDADES_ALIADAS_ART_MUS_FESTIVALES_NATURALEZA_ENTIDAD]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_ENTIDADES_ALIADAS]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_ENTIDADES_ALIADAS_ART_MUS_FESTIVALES_VERSION] FOREIGN KEY([ID_FESTIVAL])
REFERENCES [dbo].[ART_MUS_FESTIVALES_VERSION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_ENTIDADES_ALIADAS] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_ENTIDADES_ALIADAS_ART_MUS_FESTIVALES_VERSION]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_EXPRESIONXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_EXPRESIONXVERSION_ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] FOREIGN KEY([ID_EXPRESION_ARTISTICA])
REFERENCES [dbo].[ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_EXPRESIONXVERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_EXPRESIONXVERSION_ART_MUS_FESTIVALES_EXPRESIONES_ARTISTICAS]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_EXPRESIONXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_EXPRESIONXVERSION_ART_MUS_FESTIVALES_VERSION] FOREIGN KEY([ID_VERSION])
REFERENCES [dbo].[ART_MUS_FESTIVALES_VERSION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_EXPRESIONXVERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_EXPRESIONXVERSION_ART_MUS_FESTIVALES_VERSION]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION_ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] FOREIGN KEY([ID_MODALIDAD])
REFERENCES [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION_ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACION]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION_ART_MUS_FESTIVALES_VERSION] FOREIGN KEY([ID_VERSION])
REFERENCES [dbo].[ART_MUS_FESTIVALES_VERSION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_MODALIDADES_PARTICIPACIONXVERSION_ART_MUS_FESTIVALES_VERSION]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES] FOREIGN KEY([ID_FESTIVAL])
REFERENCES [dbo].[ART_MUS_FESTIVALES] ([id])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES_FUENTE_FINANCIACION] FOREIGN KEY([ID_FUENTE_FINANCIACION])
REFERENCES [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES_FUENTE_FINANCIACION]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES_FUENTE_FINANCIACION1] FOREIGN KEY([ID_FUENTE_FINANCIACION_SECUNDARIA])
REFERENCES [dbo].[ART_MUS_FESTIVALES_FUENTE_FINANCIACION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES_FUENTE_FINANCIACION1]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] FOREIGN KEY([ID_TIPO_ORGANIZADOR])
REFERENCES [dbo].[ART_MUS_FESTIVALES_TIPO_ORGANIZADOR] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES_TIPO_ORGANIZADOR]
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES_TIPOLOGIA] FOREIGN KEY([ID_TIPOLOGIA])
REFERENCES [dbo].[ART_MUS_FESTIVALES_TIPOLOGIA] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_FESTIVALES_VERSION] CHECK CONSTRAINT [FK_ART_MUS_FESTIVALES_VERSION_ART_MUS_FESTIVALES_TIPOLOGIA]
GO
ALTER TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_LOCALIZACIONXVERSION_ART_MUS_FESTIVALES_VERSION] FOREIGN KEY([ID_VERSION])
REFERENCES [dbo].[ART_MUS_FESTIVALES_VERSION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION] CHECK CONSTRAINT [FK_ART_MUS_LOCALIZACIONXVERSION_ART_MUS_FESTIVALES_VERSION]
GO
ALTER TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_LOCALIZACIONXVERSION_ART_MUS_FESTIVALES_ZONA] FOREIGN KEY([ID_ZONA])
REFERENCES [dbo].[ART_MUS_FESTIVALES_ZONA] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION] CHECK CONSTRAINT [FK_ART_MUS_LOCALIZACIONXVERSION_ART_MUS_FESTIVALES_ZONA]
GO
ALTER TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_LOCALIZACIONXVERSION_ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA] FOREIGN KEY([ID_TITULACION_COLECTIVA])
REFERENCES [dbo].[ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION] CHECK CONSTRAINT [FK_ART_MUS_LOCALIZACIONXVERSION_ART_MUS_FESTIVALES_ZONA_TITULACION_COLECTIVA]
GO
ALTER TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_LOCALIZACIONXVERSION_BAS_ZONAS_GEOGRAFICAS] FOREIGN KEY([ZON_ID])
REFERENCES [dbo].[BAS_ZONAS_GEOGRAFICAS] ([ZON_ID])
GO
ALTER TABLE [dbo].[ART_MUS_LOCALIZACIONXVERSION] CHECK CONSTRAINT [FK_ART_MUS_LOCALIZACIONXVERSION_BAS_ZONAS_GEOGRAFICAS]
GO
ALTER TABLE [dbo].[ART_MUS_MATERIALMULTIMEDIA]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_MATERIALMULTIMEDIA_ART_MUS_FESTIVALES_VERSION] FOREIGN KEY([ID_VERSION])
REFERENCES [dbo].[ART_MUS_FESTIVALES_VERSION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_MATERIALMULTIMEDIA] CHECK CONSTRAINT [FK_ART_MUS_MATERIALMULTIMEDIA_ART_MUS_FESTIVALES_VERSION]
GO
ALTER TABLE [dbo].[ART_MUS_TERRITORIOS_SONOROSXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_TERRITORIOS_SONOROSXVERSION_ART_MUS_FESTIVALES_VERSION] FOREIGN KEY([ID_VERSION])
REFERENCES [dbo].[ART_MUS_FESTIVALES_VERSION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_TERRITORIOS_SONOROSXVERSION] CHECK CONSTRAINT [FK_ART_MUS_TERRITORIOS_SONOROSXVERSION_ART_MUS_FESTIVALES_VERSION]
GO
ALTER TABLE [dbo].[ART_MUS_TERRITORIOS_SONOROSXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_TERRITORIOS_SONOROSXVERSION_ART_MUS_TERRITORIOS_SONOROS] FOREIGN KEY([ID_TERRITORIOS_SONOROS])
REFERENCES [dbo].[ART_MUS_TERRITORIOS_SONOROS] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_TERRITORIOS_SONOROSXVERSION] CHECK CONSTRAINT [FK_ART_MUS_TERRITORIOS_SONOROSXVERSION_ART_MUS_TERRITORIOS_SONOROS]
GO
ALTER TABLE [dbo].[ART_MUS_TIPOINGRESOXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_TIPOINGRESOXVERSION_ART_MUS_FESTIVALES_VERSION] FOREIGN KEY([IDVERSION])
REFERENCES [dbo].[ART_MUS_FESTIVALES_VERSION] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_TIPOINGRESOXVERSION] CHECK CONSTRAINT [FK_ART_MUS_TIPOINGRESOXVERSION_ART_MUS_FESTIVALES_VERSION]
GO
ALTER TABLE [dbo].[ART_MUS_TIPOINGRESOXVERSION]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_TIPOINGRESOXVERSION_ART_MUS_TIPOINGRESO] FOREIGN KEY([ID_TIPOINGRESO])
REFERENCES [dbo].[ART_MUS_TIPOINGRESO] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_TIPOINGRESOXVERSION] CHECK CONSTRAINT [FK_ART_MUS_TIPOINGRESOXVERSION_ART_MUS_TIPOINGRESO]
GO
ALTER TABLE [dbo].[ART_MUS_ZONAXREGION_OCAD]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_ZONAXREGION_OCAD_ART_MUS_FESTIVALES_REGION_OCAD] FOREIGN KEY([REGION_OCAD_ID])
REFERENCES [dbo].[ART_MUS_FESTIVALES_REGION_OCAD] ([ID])
GO
ALTER TABLE [dbo].[ART_MUS_ZONAXREGION_OCAD] CHECK CONSTRAINT [FK_ART_MUS_ZONAXREGION_OCAD_ART_MUS_FESTIVALES_REGION_OCAD]
GO
ALTER TABLE [dbo].[ART_MUS_ZONAXREGION_OCAD]  WITH CHECK ADD  CONSTRAINT [FK_ART_MUS_ZONAXREGION_OCAD_BAS_ZONAS_GEOGRAFICAS] FOREIGN KEY([ZON_ID])
REFERENCES [dbo].[BAS_ZONAS_GEOGRAFICAS] ([ZON_ID])
GO
ALTER TABLE [dbo].[ART_MUS_ZONAXREGION_OCAD] CHECK CONSTRAINT [FK_ART_MUS_ZONAXREGION_OCAD_BAS_ZONAS_GEOGRAFICAS]
GO
